### ISSUE TITLE
(C# 9.0) Record Support

### ISSUE THREAD

**Issue by suhyeon** [AutoReviser/AutoReviser#15]
AutoReviser cannot revise record.

`System.InvalidOperationException
  HResult=0x80131509
  메시지=Sequence contains more than one element
  소스=System.Linq
  StackTrace:
   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at AutoReviser.ConstructorResolver.Resolve[T]()
   at AutoReviser.ObjectReviser.TryRevise[T](T instance, LambdaExpression predicate, T& revision)
   at AutoReviser.Reviser.Revise[T](T instance, Expression`1 predicate)`

**Comment by gyuwon** [comment]
0.2.5 supports records!
(but not init accessors yet 😥)
